"""
티커 ↔ 한국어/영문 별칭 매핑 + 검색 함수.

사용:
    search_tickers("엔비")  → [("NVDA", "엔비디아 Nvidia"), ...]
    search_tickers("nvda")  → [("NVDA", "엔비디아 Nvidia"), ...]

검색 우선순위:
  ① 티커 정확 일치 (대소문자 무시)
  ② 티커 접두 매칭
  ③ 한국어/영문 이름 부분 매칭
"""

# (티커, "한국어이름 영문이름") — 검색은 lowercase로 substring 매칭됨
TICKER_NAMES: dict[str, str] = {
    "AAPL": "애플 Apple",
    "ABBV": "애브비 AbbVie",
    "ABNB": "에어비앤비 Airbnb",
    "ABT": "애보트 Abbott",
    "ADBE": "어도비 Adobe",
    "AEP": "아메리칸일렉트릭 American Electric Power",
    "AFRM": "어펌 Affirm",
    "ALB": "앨버말 Albemarle",
    "ALNY": "알닐람 Alnylam",
    "ALT": "알티뮨 Altimmune",
    "AMAT": "어플라이드머티리얼즈 Applied Materials",
    "AMD": "에이엠디 AMD",
    "AMGN": "암젠 Amgen",
    "AMKR": "앰코테크놀로지 Amkor",
    "AMT": "아메리칸타워 American Tower",
    "AMX": "아메리카모빌 America Movil",
    "AMZN": "아마존 Amazon",
    "ANET": "아리스타네트웍스 Arista Networks",
    "APD": "에어프로덕츠 Air Products",
    "ARM": "에이알엠 Arm Holdings",
    "ASML": "에이에스엠엘 ASML",
    "ASTS": "AST 스페이스모바일 AST SpaceMobile",
    "AVAV": "에어로바이런먼트 AeroVironment",
    "AVB": "아발론베이 AvalonBay Communities",
    "AVGO": "브로드컴 Broadcom",
    "AZN": "아스트라제네카 AstraZeneca",
    "BA": "보잉 Boeing",
    "BAC": "뱅크오브아메리카 Bank of America",
    "BCE": "비씨이 BCE",
    "BE": "블룸에너지 Bloom Energy",
    "BIIB": "바이오젠 Biogen",
    "BKNG": "부킹홀딩스 Booking Holdings",
    "BKSY": "블랙스카이 BlackSky",
    "BLDP": "발라드파워 Ballard Power",
    "BLK": "블랙록 BlackRock",
    "BMRN": "바이오마린 BioMarin",
    "BMY": "브리스톨마이어스스큅 Bristol-Myers Squibb",
    "BNTX": "바이오엔텍 BioNTech",
    "BWXT": "BWX 테크놀로지 BWX Technologies",
    "BX": "블랙스톤 Blackstone",
    "C": "씨티그룹 Citigroup",
    "CAT": "캐터필러 Caterpillar",
    "CCI": "크라운캐슬 Crown Castle",
    "CCJ": "카메코 Cameco",
    "CCL": "카니발 Carnival",
    "CCOI": "코젠트커뮤니케이션즈 Cogent Communications",
    "CDNS": "케이던스 Cadence Design",
    "CEG": "컨스텔레이션에너지 Constellation Energy",
    "CHPT": "차지포인트 ChargePoint",
    "CHRW": "씨에이치로빈슨 C.H. Robinson",
    "CHTR": "차터커뮤니케이션즈 Charter Communications",
    "CIEN": "시에나 Ciena",
    "CL": "콜게이트팜올리브 Colgate-Palmolive",
    "CMCSA": "컴캐스트 Comcast",
    "CMG": "치폴레 Chipotle",
    "CMI": "커민스 Cummins",
    "COHR": "코히어런트 Coherent",
    "COIN": "코인베이스 Coinbase",
    "COP": "코노코필립스 ConocoPhillips",
    "COST": "코스트코 Costco",
    "CRM": "세일즈포스 Salesforce",
    "CRSP": "크리스퍼테라퓨틱스 CRISPR Therapeutics",
    "CRWD": "크라우드스트라이크 CrowdStrike",
    "CSCO": "시스코 Cisco",
    "CSX": "씨에스엑스 CSX",
    "CTVA": "코르테바 Corteva",
    "CVX": "셰브론 Chevron",
    "D": "도미니언에너지 Dominion Energy",
    "DAL": "델타항공 Delta Air Lines",
    "DD": "듀폰 DuPont",
    "DDOG": "데이터독 Datadog",
    "DE": "디어앤컴퍼니 Deere",
    "DELL": "델 Dell Technologies",
    "DIS": "디즈니 Disney",
    "DLR": "디지털리얼티 Digital Realty",
    "DOW": "다우 Dow",
    "DPZ": "도미노피자 Domino's Pizza",
    "DUK": "듀크에너지 Duke Energy",
    "DXCM": "덱스콤 DexCom",
    "EA": "일렉트로닉아츠 Electronic Arts",
    "ECL": "에코랩 Ecolab",
    "ED": "콘솔리데이티드에디슨 Consolidated Edison",
    "EMR": "에머슨일렉트릭 Emerson Electric",
    "ENPH": "엔페이즈에너지 Enphase Energy",
    "ENTG": "엔테그리스 Entegris",
    "EOG": "EOG 리소시즈 EOG Resources",
    "EQIX": "에퀴닉스 Equinix",
    "ETN": "이튼 Eaton",
    "EXC": "엑셀론 Exelon",
    "EXPD": "익스피디터스 Expeditors",
    "EXPE": "익스피디아 Expedia",
    "EXR": "엑스트라스페이스 Extra Space Storage",
    "F": "포드 Ford",
    "FANG": "다이아몬드백에너지 Diamondback Energy",
    "FANUY": "화낙 FANUC",
    "FAST": "패스널 Fastenal",
    "FCX": "프리포트맥모란 Freeport-McMoRan",
    "FDX": "페덱스 FedEx",
    "FOUR": "시프트4페이먼츠 Shift4 Payments",
    "FOXA": "폭스 Fox",
    "FSLR": "퍼스트솔라 First Solar",
    "FTNT": "포티넷 Fortinet",
    "FWONK": "리버티미디어 포뮬러원 Liberty Media Formula One",
    "GD": "제너럴다이내믹스 General Dynamics",
    "GE": "GE 에어로스페이스 GE Aerospace",
    "GEN": "젠디지털 Gen Digital Norton",
    "GEV": "GE 버노바 GE Vernova",
    "GILD": "길리어드 Gilead Sciences",
    "GIS": "제너럴밀스 General Mills",
    "GM": "제너럴모터스 General Motors",
    "GOOGL": "구글 알파벳 Alphabet Google",
    "GS": "골드만삭스 Goldman Sachs",
    "H": "하얏트 Hyatt Hotels",
    "HD": "홈디포 Home Depot",
    "HII": "헌팅턴인갈스 Huntington Ingalls",
    "HLT": "힐튼 Hilton",
    "HON": "허니웰 Honeywell",
    "HOOD": "로빈후드 Robinhood",
    "HPE": "휴렛팩커드엔터프라이즈 HPE Hewlett Packard Enterprise",
    "HSY": "허쉬 Hershey",
    "IBM": "아이비엠 IBM",
    "IDXX": "아이덱스 Idexx Laboratories",
    "ILMN": "일루미나 Illumina",
    "INTC": "인텔 Intel",
    "IONQ": "아이온큐 IonQ",
    "IONS": "아이오니스 Ionis Pharmaceuticals",
    "IRDM": "이리듐 Iridium Communications",
    "IRM": "아이언마운틴 Iron Mountain",
    "ISRG": "인튜이티브서지컬 Intuitive Surgical",
    "ITW": "일리노이툴웍스 Illinois Tool Works",
    "JBHT": "제이비헌트 J.B. Hunt",
    "JNJ": "존슨앤존슨 Johnson Johnson",
    "JPM": "JP 모건 JPMorgan Chase",
    "KLAC": "케이엘에이 KLA",
    "KMB": "킴벌리클라크 Kimberly-Clark",
    "KMI": "킨더모건 Kinder Morgan",
    "KO": "코카콜라 Coca-Cola",
    "KTOS": "크라토스 Kratos Defense",
    "LCID": "루시드 Lucid Motors",
    "LHX": "L3해리스 L3Harris",
    "LI": "리오토 Li Auto",
    "LIN": "린데 Linde",
    "LIT": "글로벌X 리튬 ETF Global X Lithium",
    "LITE": "루멘텀 Lumentum",
    "LLY": "일라이릴리 Eli Lilly",
    "LMT": "록히드마틴 Lockheed Martin",
    "LOW": "로우스 Lowe's",
    "LRCX": "램리서치 Lam Research",
    "LUMN": "루멘테크놀로지 Lumen Technologies",
    "LUV": "사우스웨스트항공 Southwest Airlines",
    "LVS": "라스베이거스샌즈 Las Vegas Sands",
    "LYV": "라이브네이션 Live Nation",
    "MA": "마스터카드 Mastercard",
    "MAR": "메리어트 Marriott",
    "MBLY": "모빌아이 Mobileye",
    "MCD": "맥도날드 McDonald's",
    "MDB": "몽고디비 MongoDB",
    "MDLZ": "몬델리즈 Mondelez",
    "MDT": "메드트로닉 Medtronic",
    "MELI": "메르카도리브레 MercadoLibre",
    "META": "메타 페이스북 Meta Facebook",
    "MGM": "MGM 리조트 MGM Resorts",
    "MKSI": "MKS 인스트루먼츠 MKS Instruments",
    "MMM": "쓰리엠 3M",
    "MNST": "몬스터베버리지 Monster Beverage",
    "MPC": "마라톤페트롤리엄 Marathon Petroleum",
    "MRK": "머크 Merck",
    "MRNA": "모더나 Moderna",
    "MS": "모건스탠리 Morgan Stanley",
    "MSFT": "마이크로소프트 Microsoft",
    "MSTR": "마이크로스트레티지 MicroStrategy Strategy",
    "MU": "마이크론테크놀로지 Micron",
    "NCLH": "노르웨이지언크루즈 Norwegian Cruise Line",
    "NEE": "넥스트에라에너지 NextEra Energy",
    "NEM": "뉴몬트 Newmont",
    "NET": "클라우드플레어 Cloudflare",
    "NFLX": "넷플릭스 Netflix",
    "NIO": "니오 NIO",
    "NKE": "나이키 Nike",
    "NOC": "노스롭그루먼 Northrop Grumman",
    "NOK": "노키아 Nokia",
    "NOW": "서비스나우 ServiceNow",
    "NRG": "NRG 에너지 NRG Energy",
    "NSC": "노퍽서던 Norfolk Southern",
    "NU": "누홀딩스 누뱅크 Nu Holdings Nubank",
    "NUE": "뉴코 Nucor",
    "NVDA": "엔비디아 Nvidia",
    "NVO": "노보노디스크 Novo Nordisk",
    "NVS": "노바티스 Novartis",
    "NWSA": "뉴스코프 News Corp",
    "O": "리얼티인컴 Realty Income",
    "ODFL": "올드도미니언 Old Dominion Freight",
    "OKTA": "옥타 Okta",
    "ONTO": "온토이노베이션 Onto Innovation",
    "ORCL": "오라클 Oracle",
    "OUST": "아우스터 Ouster",
    "OXY": "옥시덴탈페트롤리엄 Occidental Petroleum",
    "PANW": "팔로알토네트웍스 Palo Alto Networks",
    "PCG": "퍼시픽가스 PG&E",
    "PEP": "펩시코 PepsiCo",
    "PFE": "화이자 Pfizer",
    "PG": "프록터앤갬블 P&G Procter Gamble",
    "PH": "파커하니핀 Parker Hannifin",
    "PL": "플래닛랩스 Planet Labs",
    "PLD": "프롤로지스 Prologis",
    "PLTR": "팔란티어 Palantir",
    "PLUG": "플러그파워 Plug Power",
    "PNC": "피엔씨 PNC Financial",
    "PSA": "퍼블릭스토리지 Public Storage",
    "PSX": "필립스66 Phillips 66",
    "PYPL": "페이팔 PayPal",
    "QBTS": "디웨이브 D-Wave Quantum",
    "QCOM": "퀄컴 Qualcomm",
    "QS": "퀀텀스케이프 QuantumScape",
    "QUBT": "퀀텀컴퓨팅 Quantum Computing Inc",
    "RBLX": "로블록스 Roblox",
    "RCL": "로열캐리비안 Royal Caribbean",
    "REGN": "리제네론 Regeneron",
    "RGTI": "리게티컴퓨팅 Rigetti Computing",
    "RIVN": "리비안 Rivian",
    "RKLB": "로켓랩 Rocket Lab",
    "ROK": "록웰오토메이션 Rockwell Automation",
    "ROST": "로스스토어스 Ross Stores",
    "RPD": "래피드7 Rapid7",
    "RTX": "RTX 레이시온 Raytheon",
    "RUN": "선런 Sunrun",
    "S": "센티넬원 SentinelOne",
    "SBUX": "스타벅스 Starbucks",
    "SCHW": "찰스슈왑 Charles Schwab",
    "SEDG": "솔라엣지 SolarEdge",
    "SHW": "셔윈윌리엄스 Sherwin-Williams",
    "SLB": "슐럼버거 SLB Schlumberger",
    "SMCI": "슈퍼마이크로 Super Micro Computer",
    "SMR": "뉴스케일파워 NuScale Power",
    "SNOW": "스노우플레이크 Snowflake",
    "SNPS": "시놉시스 Synopsys",
    "SO": "서던컴퍼니 Southern Company",
    "SOFI": "소파이 SoFi",
    "SPCE": "버진갤럭틱 Virgin Galactic",
    "SPG": "사이먼프로퍼티 Simon Property",
    "SPOT": "스포티파이 Spotify",
    "SRE": "셈프라 Sempra Energy",
    "STLA": "스텔란티스 Stellantis",
    "SYK": "스트라이커 Stryker",
    "SYM": "심보틱 Symbotic",
    "T": "에이티앤티 AT&T",
    "TDG": "트랜스다임 TransDigm",
    "TEAM": "아틀라시안 Atlassian",
    "TER": "테라다인 Teradyne",
    "TFC": "트루이스트 Truist Financial",
    "TJX": "티제이엑스 TJX Companies",
    "TMUS": "티모바일 T-Mobile US",
    "TSLA": "테슬라 Tesla",
    "TSM": "TSMC 티에스엠씨 Taiwan Semiconductor",
    "TTWO": "테이크투 Take-Two Interactive",
    "TXN": "텍사스인스트루먼츠 Texas Instruments",
    "UAL": "유나이티드항공 United Airlines",
    "UNP": "유니언퍼시픽 Union Pacific",
    "UPS": "유피에스 UPS United Parcel",
    "USB": "유에스뱅코프 U.S. Bancorp",
    "V": "비자 Visa",
    "VICI": "비치프로퍼티스 VICI Properties",
    "VKTX": "바이킹테라퓨틱스 Viking Therapeutics",
    "VLO": "밸러로에너지 Valero Energy",
    "VMC": "벌컨머티리얼즈 Vulcan Materials",
    "VOD": "보다폰 Vodafone",
    "VRNS": "바로니스 Varonis Systems",
    "VRT": "버티브 Vertiv",
    "VRTX": "버텍스파마 Vertex Pharmaceuticals",
    "VST": "비스트라 Vistra",
    "VZ": "버라이즌 Verizon",
    "WBD": "워너브라더스디스커버리 Warner Bros Discovery",
    "WDAY": "워크데이 Workday",
    "WELL": "웰타워 Welltower",
    "WFC": "웰스파고 Wells Fargo",
    "WMB": "윌리엄스컴퍼니즈 Williams Companies",
    "WMG": "워너뮤직그룹 Warner Music Group",
    "WMT": "월마트 Walmart",
    "WYNN": "윈리조트 Wynn Resorts",
    "XEL": "엑셀에너지 Xcel Energy",
    "XOM": "엑손모빌 Exxon Mobil",
    "XPEV": "샤오펑 XPeng",
    "XYZ": "블록 스퀘어 Block Square",
    "ZS": "지스케일러 Zscaler",
}


def search_tickers(query: str, limit: int = 8) -> list[tuple[str, str]]:
    """
    입력 문자열에 매칭되는 (ticker, 별칭) 후보를 우선순위 순으로 반환.

    우선순위:
      0 = 티커 정확 일치 (예: 'nvda' → NVDA)
      1 = 티커 접두 매칭 (예: 'nv' → NVDA, NVO, NVS)
      2 = 한국어/영문 이름 부분 매칭 (예: '엔비' → NVDA)
    """
    q = (query or "").strip()
    if not q:
        return []
    ql = q.lower()
    qu = q.upper()

    scored: list[tuple[int, str, str]] = []
    seen: set[str] = set()

    # ① 티커 정확 일치
    if qu in TICKER_NAMES and qu not in seen:
        scored.append((0, qu, TICKER_NAMES[qu]))
        seen.add(qu)

    # ② 티커 접두 매칭
    for tk, name in TICKER_NAMES.items():
        if tk in seen:
            continue
        if tk.startswith(qu):
            scored.append((1, tk, name))
            seen.add(tk)

    # ③ 이름 부분 매칭
    for tk, name in TICKER_NAMES.items():
        if tk in seen:
            continue
        if ql in name.lower():
            scored.append((2, tk, name))
            seen.add(tk)

    scored.sort(key=lambda x: (x[0], x[1]))
    return [(tk, name) for _, tk, name in scored[:limit]]


def display_name(ticker: str) -> str:
    """'NVDA' → '엔비디아 (NVDA)' 형식. 미등록 티커는 그냥 티커 반환."""
    name = TICKER_NAMES.get(ticker.upper())
    if not name:
        return ticker
    ko = name.split()[0]  # 첫 토큰이 보통 한국어
    return f"{ko} ({ticker.upper()})"
